version: '3'
services:
  api:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    networks:
      - api-network
    restart: always
    volumes:
      - /usr/app/node_modules

  jobs:
    build:
      context: .
      dockerfile: src/jobs/Dockerfile
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - 3002:3002
    networks:
      - api-network
    restart: always
    volumes:
      - /usr/app/node_modules

networks:
  api-network:
    driver: bridge
